language: php
php:
  - '5.6'
  - '7.1'
  - nightly

before-script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true

notifications:
   on_success: never
   on_failure: always