sudo: required

language: php
php:
  - '7.1'
  - nightly

services:
  - docker

before install:
  - docker pull yzuellig/message-board

install: composer install

before-script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --configuration phpunit.xml

matrix:
  fast_finish: true

notifications:
   on_success: never
   on_failure: always